---
- name: Push-Based CD Deployment to OpenShift
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Apply Spring Boot Deployment Manifest
      kubernetes.core.k8s:
        host: "{{ lookup('env', 'OPENSHIFT_SERVER') }}"
        api_key: "{{ lookup('env', 'OPENSHIFT_TOKEN') }}"
        validate_certs: no
        state: present
        src: deployment.yaml
        namespace: l3ti-me20-dev

    - name: Apply Spring Boot Service Manifest
      kubernetes.core.k8s:
        host: "{{ lookup('env', 'OPENSHIFT_SERVER') }}"
        api_key: "{{ lookup('env', 'OPENSHIFT_TOKEN') }}"
        validate_certs: no
        state: present
        src: service.yaml
        namespace: l3ti-me20-dev