---
- name: Push-Based CD Deployment to Local Docker
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Ensure the Spring Boot application container is running
      community.docker.docker_container:
        name: enterprise-app-container
        image: "{{ lookup('env', 'NEXUS_REGISTRY') }}/{{ lookup('env', 'IMAGE_NAME') }}:{{ lookup('env', 'BUILD_NUMBER') | default('latest') }}"
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
        env:
          SPRING_CLOUD_VAULT_HOST: "host.docker.internal"
          SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://host.docker.internal:9090/realms/enterprise-realm"