apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api-svc
  namespace: l3ti-me20-dev
spec:
  selector:
    # This exactly matches the label of your Spring Boot container
    app: spring-boot-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP